version: 37
jobs:
- name: GitHub Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Data.Caching.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/VNLib.Data.Caching.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: VNLib.Data.Caching
  - !BranchUpdateTrigger
    projects: VNLib.Data.Caching
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Unit Testing
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone local deps
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/VNLib.Plugins.Extensions --branch master
        git clone @server_url@/@project_name@ --branch @branch@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run unit tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild test --include @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Staging build
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone local deps
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/VNLib.Plugins.Extensions --branch master
        git clone @server_url@/@project_name@ --branch @branch@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        dotnet gitversion VNLib.Plugins.Extensions /updateprojectfiles
        vnbuild build --no-delay --include vnlib.core
        vnbuild build --no-delay --include @project_name@ --verbose
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: mock publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: publish server artifacts
    sourcePath: '@project_name@/server/bin'
    artifacts: '*'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Unit Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Publish master
  jobExecutor: publish-agents
  steps:
  - !CommandStep
    name: Clone local deps
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/VNLib.Plugins.Extensions --branch master
        git clone @server_url@/@project_name@ --branch @branch@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Create git tag
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml tag-current-commit
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        dotnet gitversion VNLib.Plugins.Extensions /updateprojectfiles
        vnbuild build --no-delay --include vnlib.core
        vnbuild build --no-delay --include @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@ --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: publish server artifacts
    sourcePath: '@project_name@/server/bin'
    artifacts: '*'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: build image
  jobExecutor: docker
  steps:
  - !CommandStep
    name: prep image
    runInContainer: true
    image: ubuntu:25.04
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        ls -lah
        tar -xzf container-release.tgz
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: build docker-hub image
    buildPath: '@project_name@'
    output: !RegistryOutput
      tags: vnuge/vncache:ubuntu-@branch@ vnuge/vncache:ubuntu-@commit_hash@
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Staging build
    requireSuccessful: true
    artifacts: '**'
    destinationPath: '@project_name@'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: build master image
  jobExecutor: docker
  steps:
  - !CommandStep
    name: prep image
    runInContainer: true
    image: ubuntu:25.04
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        ls -lah
        tar -xzf container-release.tgz
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: build docker-hub image
    buildPath: '@project_name@'
    output: !RegistryOutput
      tags: vnuge/vncache:ubuntu-latest vnuge/vncache:ubuntu-@branch@ vnuge/vncache:ubuntu-@commit_hash@
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger 
    branches: master
  jobDependencies:
  - jobName: Publish master
    requireSuccessful: true
    artifacts: '**'
    destinationPath: '@project_name@'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
