version: 40
properties:
- name: deps_core_version
  value: master/v0.1.2-rc.10
  archived: false
- name: deps_extensions_version
  value: master/v0.1.2-rc.7
  archived: false

jobs:
- name: Git Mirror Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Data.Caching.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: false
    condition: SUCCESSFUL
    optional: false
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/VNLib.Data.Caching.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !TagCreateTrigger {}
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Unit Testing
  jobExecutor: windows
  steps:
  - !UseTemplateStep
    name: init deps
    templateName: checkout deps
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: run unit tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild test --include @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Windows CI Tests
  jobExecutor: windows
  steps:
  - !UseTemplateStep
    name: init deps
    templateName: checkout deps
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: build modules
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --no-delay --include vnlib.core
        vnbuild build --no-delay --include @project_name@ --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: run integration tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        cd tests/integration-tests
        task setup-server
        task test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Staging build
  jobExecutor: windows
  steps:
  - !UseTemplateStep
    name: init deps
    templateName: checkout deps
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: mock build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --no-delay --include vnlib.core
        vnbuild build --no-delay --include @project_name@ --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: mock publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !PublishArtifactStep
    name: publish server artifacts
    sourcePath: '@project_name@/server/bin'
    artifacts: '*'
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Unit Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Publish master
  jobExecutor: publish-agents
  steps:
  - !UseTemplateStep
    name: init deps
    templateName: checkout deps
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Create git tag
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml tag-current-commit
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --no-delay --include vnlib.core
        vnbuild build --no-delay --include @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@ --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !PublishArtifactStep
    name: publish server artifacts
    sourcePath: '@project_name@/server/bin'
    artifacts: '*'
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: build image
  jobExecutor: docker
  steps:
  - !CommandStep
    name: prep image
    runInContainer: true
    image: ubuntu:25.04
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        ls -lah
        tar -xzf container-release.tgz
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !BuildImageStep
    name: build docker-hub image
    buildPath: '@project_name@'
    output: !RegistryOutput
      tags: vnuge/vncache:ubuntu-@branch@ vnuge/vncache:ubuntu-@commit_hash@
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Staging build
    requireSuccessful: true
    artifacts: '**'
    destinationPath: '@project_name@'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: build master image
  jobExecutor: docker
  steps:
  - !CommandStep
    name: prep image
    runInContainer: true
    image: ubuntu:25.04
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        ls -lah
        tar -xzf container-release.tgz
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !BuildImageStep
    name: build docker-hub image
    buildPath: '@project_name@'
    output: !RegistryOutput
      tags: vnuge/vncache:ubuntu-latest vnuge/vncache:ubuntu-@branch@ vnuge/vncache:ubuntu-@commit_hash@
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: master
  jobDependencies:
  - jobName: Publish master
    requireSuccessful: true
    artifacts: '**'
    destinationPath: '@project_name@'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

stepTemplates:
- name: checkout deps
  steps:
  - !CommandStep
    name: checkout local deps
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
        task -t @project_name@/Module.Taskfile.yaml configure-dep "DEP_REPO=@server_url@/vnuge/vnlib/VNLib.Core" "DEP_REVISION=@property:deps_core_version@" "DEP_DIR=core"
        task -t @project_name@/Module.Taskfile.yaml configure-dep "DEP_REPO=@server_url@/vnuge/vnlib/VNLib.Plugins.Extensions" "DEP_REVISION=@property:deps_extensions_version@"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
