# https://taskfile.dev

#Called by the vnbuild system to produce builds for my website
#https://www.vaughnnugent.com/resources/software

version: "3"

includes:
  install:
    taskfile: install.taskfile.yaml

  plugins:
    taskfile: plugins.taskfile.yaml

  container:
    dir: container  #always run from the container directory
    taskfile: container/Taskfile.yaml
    vars:
      PACKAGE_FILE_NAME: "vncache-oci.tgz"  #the name of the output package file

tasks:

  build:
    deps:
      - task: plugins:all
      - task: compile-config
    cmds:

    - cmd: powershell "mkdir -Force lib/"
      ignore_error: true

     #remove runtime-shared libs before they are copied
    - task: prune-plugin-libs

    - task: parallel-envs

    #run container build last
    - task: container:build

  parallel-envs:
    deps:
     - task: create-env
       vars: { TARGET_OS: 'windows-x86_64' }
     - task: create-env
       vars: { TARGET_OS: 'linux-x86_64' }
     - task: create-env
       vars: { TARGET_OS: 'osx-x86_64' }
     - task: create-env
       vars: { TARGET_OS: 'windows-arm' }
     - task: create-env
       vars: { TARGET_OS: 'linux-arm' }
     - task: create-env
       vars: { TARGET_OS: 'osx-arm' }

  create-env:
    vars:
      BUILD_DIR: './build/{{.TARGET_OS}}'
    cmds:
    #create dir for env
    - cmd: powershell -Command "mkdir {{ .BUILD_DIR }} -Force"
      ignore_error: true
    
    #copy build files for target os
    - for: [ plugins, lib, config, webserver, config ]
      cmd: powershell cp -Recurse -Force "{{ .ITEM }}" "{{ .BUILD_DIR }}"

    #copy release taskfile and rename it
    - cmd: powershell cp -Force release.taskfile.yaml "{{ .BUILD_DIR }}/Taskfile.yaml"
 
  pack:
    internal: true
    vars:
      TAR_OUT_DIR: '{{ .USER_WORKING_DIR }}/{{ .BINARY_DIR }}'
    cmds:
    - cmd: powershell mkdir -Force "build/{{.TARGET_OS}}/"
      ignore_error: true
    - cmd: cd build/{{ .TARGET_OS }} && tar -czf "{{ .TAR_OUT_DIR }}/{{ .TARGET_OS }}-release.tgz" . 

  compile-config:
    internal: false
    dotenv: ['build.env']  #use the local .env file when compiling config variables
    cmds:
     - cmd: powershell mkdir config/ -Force
       ignore_error: true
     - cmd: powershell './compile.ps1' -InputDir config-templates/ -OutputDir config/
     
  prune-plugin-libs:
    cmds:
    - for: ['vnlib.utils.dll' , 'vnlib.net.http.dll', 'VNLib.Hashing.Portable.dll', 'VNLib.Plugins.Essentials.dll', 'VNLib.Plugins.dll', 'Serilog.dll', 'Serilog.Sinks.Console.dll', 'Serilog.Sinks.File.dll']
      cmd: cd plugins && powershell 'Get-ChildItem -Path . -Recurse -File -Filter "{{.ITEM}}" | Remove-Item -Force'

  postbuild_success:
    cmds:
    - cmd: powershell -Command "mkdir bin -Force"
    - task: pb-parallel

    #cleanup unnecessary build files that clog up the pipeline
    - for: [ build, plugins, lib, webserver, config ]
      cmd: powershell -Command "rm -Recurse '{{.ITEM}}'"
      ignore_error: true

    - task: container:postbuild_success

  pb-parallel:
    internal: true
    deps:
     - task: pack
       vars: { TARGET_OS: 'windows-x86_64' }
     - task: pack
       vars: { TARGET_OS: 'linux-x86_64' }
     - task: pack
       vars: { TARGET_OS: 'osx-x86_64' }
     - task: pack
       vars: { TARGET_OS: 'windows-arm' }
     - task: pack
       vars: { TARGET_OS: 'linux-arm' }
     - task: pack
       vars: { TARGET_OS: 'osx-arm' }
    cmds:
    - echo "Packing complete"

  clean:
    ignore_error: true
    cmds:
    - for: [ build/, bin/, plugins/, lib/, webserver/, config/ ]
      cmd: powershell -Command "rm -Recurse -Force '{{.ITEM}}'"
    
    - task: container:clean